# Summary: Chart Metadata for GitOps App of Apps
# Description:
# Defines the Helm metadata for the parent chart that manages
# all ArgoCD Applications for the ShvikiFitness environment.

apiVersion: v2
name: shviki-fitness-gitops
description: Argo CD App of Apps for ShvikiFitness Capstone
version: 1.0.0
